/****** Object:  Table [dbo].[TB_MALL_ORDER]    Script Date: 2021-11-04 오후 8:01:00 ******/
-- 백화점 온라인몰 주문 정보
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_MALL_ORDER](
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[NO_SEQ] [int] NULL,
	[CUST_NAME] [varchar](50) NULL,
	[CUST_PHONE] [varchar](20) NULL,
	[ETC] [varchar](40) NULL,
	[MALL] [tinyint] NULL,
 CONSTRAINT [PK_TB_MALL_ORDER_SEQ] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[TB_MALL_RETURN]    Script Date: 2021-11-04 오후 8:01:00 ******/
-- 백화점 온라인몰 반품 정보
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TB_MALL_RETURN](
	[SEQ] [int] IDENTITY(1,1) NOT NULL,
	[NO_SEQ] [int] NULL,
	[CUST_NAME] [varchar](20) NULL,
	[CUST_PHONE] [varchar](20) NULL,
	[ETC] [varchar](40) NULL,
	[MALL] [tinyint] NULL,
 CONSTRAINT [PK_TB_MALL_RETURN_SEQ] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
