USE [WOORIM_230215]
GO

/****** Object:  View [dbo].[LEADER_V_PRODUCT_OPTION]    Script Date: 2023-02-15 오전 11:24:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE   VIEW [dbo].[LEADER_V_PRODUCT_OPTION] 
AS

	SELECT	AA.OWNMALL_MODEL_NO 
		   ,AA.SET_GUBUN 
		   ,AA.BRAND_NAME
		   ,AA.MODELNO
		   ,AA.MODELNO2
		   ,AA.OPTIONYN	--옵션사용유무
		   --길이/사이즈
		   ,CASE WHEN AA.CATEGORY IN ('R','C') THEN ROUND(AA.MINSIZE,0) ELSE AA.MINSIZE END AS MINSIZE --최소사이즈
		   ,CASE WHEN AA.CATEGORY IN ('R','C') THEN FLOOR(AA.MAXSIZE) ELSE AA.MAXSIZE END AS MAXSIZE --최대사이즈
		   ,AA.UNIT --단위
		   ,AA.UNITPRICE --옵션 가격(사이즈,길이)
		   ,AA.READYMADESIZE --기성사이즈
		   --각인
		   ,AA.ENGRAVE_DISPLAY   --각인 노출
		   ,AA.ENGRAVE_PRICE --각인추가금액
		   --색상
		   ,AA.COLOR AS COLOR_DISPLAY --색상
			-- 옵션값에 추가옵션가격을 붙일지 판단. 추가옵션가격이 있는 색상이 기성색상과 같으면 가격은 0
		   ,CASE WHEN AA.RG = '1' AND CHARINDEX('RG',AA.COLOR_PRICE) > 0 AND AA.READYMADECOLOR <> 'RG' 
						THEN (SELECT ','+ SUB_CD_1 FROM TB_COM_CODE WHERE GRP_CD = 'OWN_OPT_COLOR_PRICE' AND COM_NM = 'RG' )	ELSE IIF(AA.RG='1',',0','')  END +
			CASE WHEN AA.YG = '1' AND CHARINDEX('YG',AA.COLOR_PRICE) > 0 AND AA.READYMADECOLOR <> 'YG'  
						THEN (SELECT ','+ SUB_CD_1 FROM TB_COM_CODE WHERE GRP_CD = 'OWN_OPT_COLOR_PRICE' AND COM_NM = 'YG' )	ELSE IIF(AA.YG='1',',0','') END +
			CASE WHEN AA.WG = '1' AND CHARINDEX('WG',AA.COLOR_PRICE) > 0 AND CHARINDEX('WG(무도금)',AA.COLOR_PRICE) = 0 AND AA.READYMADECOLOR <> 'WG'  
						THEN (SELECT ','+ SUB_CD_1 FROM TB_COM_CODE WHERE GRP_CD = 'OWN_OPT_COLOR_PRICE' AND COM_NM = 'WG' )	ELSE IIF(AA.WG='1',',0','') END +
			CASE WHEN AA.WGX= '1' AND CHARINDEX('WG(무도금)',AA.COLOR_PRICE) > 0 AND AA.READYMADECOLOR <> 'WG(무도금)'   
						THEN (SELECT ','+ SUB_CD_1 FROM TB_COM_CODE WHERE GRP_CD = 'OWN_OPT_COLOR_PRICE' AND COM_NM = 'WG(무도금)' )	ELSE IIF(AA.WGX='1',',0','') END +
			CASE WHEN AA.CB = '1' AND CHARINDEX('CB',AA.COLOR_PRICE) > 0 AND AA.READYMADECOLOR <> 'CB'   
						THEN (SELECT ','+ SUB_CD_1 FROM TB_COM_CODE WHERE GRP_CD = 'OWN_OPT_COLOR_PRICE' AND COM_NM = 'CB' )	ELSE IIF(AA.CB='1',',0','') END AS COLOR_PRICE --색상 추가금액		
		   ,AA.READYMADECOLOR --기성색상

		   --스톤
		   ,SUBSTRING(AA.STONE_DISPLAY,2,LEN(AA.STONE_DISPLAY)) AS STONE_DISPLAY --스톤 노출
		   ,AA.READYMADESTONE --기성스톤
		   ,AA.CATEGORY 
	FROM	(
				SELECT	A.MODELNO						AS OWNMALL_MODEL_NO 
					   ,A.GUBUN							AS SET_GUBUN 
					   ,B.BRANDNAME						AS BRAND_NAME--브랜드명
					   ,P.MODELNO						AS MODELNO
					   ,P.ERP_CD_ITEM					AS MODELNO2
					   ,ISNULL(S.OPTIONYN,'N') AS OPTIONYN	--옵션사용유무
					   --길이/사이즈
					   ,S.MINSIZE --최소사이즈
					   ,S.MAXSIZE --최대사이즈
					   ,S.UNIT --단위
					   ,ISNULL(S.UNITPRICE,0)			AS UNITPRICE--옵션 가격
					   ,S.READYMADESIZE --기성사이즈(반지사이즈, 길이)
					   --각인
					   ,ISNULL(S.ENGRAVE,'N')			AS ENGRAVE --각인사용여부
					   ,CASE WHEN S.ENGRAVE = 'Y' THEN ',미사용, 사용' END AS ENGRAVE_DISPLAY   --각인사용여부
					   ,CASE WHEN S.ENGRAVE = 'Y' THEN ',0,'+ C.SUB_CD_1 END AS ENGRAVE_PRICE --각인추가금액
					   --색상
					   ,S.RG
					   ,S.YG
					   ,S.WG
					   ,S.WGX
					   ,S.CB
					   ,CASE WHEN S.RG = '1' THEN ',RG'			ELSE '' END +
						CASE WHEN S.YG = '1' THEN ',YG'			ELSE '' END +
						CASE WHEN S.WG = '1' THEN ',WG'			ELSE '' END +
						CASE WHEN S.WGX= '1' THEN ',WG(무도금)'	ELSE '' END +
						CASE WHEN S.CB = '1' THEN ',CB'			ELSE '' END AS COLOR

					   ,CASE WHEN SUBSTRING(P.ERP_CD_ITEM,14,1) = 'R' THEN 'RG'
							 WHEN SUBSTRING(P.ERP_CD_ITEM,14,1) = 'Y' THEN 'YG'
							 WHEN SUBSTRING(P.ERP_CD_ITEM,14,1) = 'W' THEN 'WG'
							 WHEN SUBSTRING(P.ERP_CD_ITEM,14,1) = 'X' THEN 'WG(무도금)'
							 WHEN SUBSTRING(P.ERP_CD_ITEM,14,1) = 'C' THEN 'CB' END AS READYMADECOLOR --기성색상
						,(SELECT ',' + COM_NM FROM TB_COM_CODE WHERE GRP_CD = 'OWN_OPT_COLOR_PRICE' FOR XML PATH('')) AS COLOR_PRICE
						--스톤
					   ,D.COM_NM AS READYMADESTONE --기성스톤
					   ,CASE WHEN ISNULL(S.READYMADESTONE,'') = '04' THEN  (SELECT ',' + COM_NM FROM TB_COM_CODE WHERE GRP_CD = 'OWN_OPT_STONE' FOR XML PATH('')) END AS STONE_DISPLAY -- 스톤노출
					   --
					   ,CASE WHEN LEN(P.ERP_CD_ITEM) = 18 AND CHARINDEX('-', P.ERP_CD_ITEM) > 0 THEN LEFT(RIGHT(P.ERP_CD_ITEM, CHARINDEX('-', REVERSE(P.ERP_CD_ITEM))-1),1) END AS CATEGORY
				FROM (	   
						SELECT MODELNO, FULLMODELNO, 1 AS QTY, SEQ, 'P' AS GUBUN
						FROM ECOMMERCEPRODUCT
						UNION ALL
						SELECT MODELNO, FULLMODELNO, SQTY AS QTY, SEQ, 'S' AS GUBUN
						FROM ECOMMERCESETPRODUCT
					 ) A 
					 INNER JOIN WOORIM.DBO.PRODUCT P ON P.MODELNO = A.FULLMODELNO
					 INNER JOIN BRANDNAME B ON B.SEQ = P.BRANDSEQ 
					 INNER JOIN TB_OWNMALL_BRAND_STORE_MAPPING E ON E.BRAND_SEQ = B.SEQ  
					 LEFT JOIN WOORIM.DBO.STYLEBOOK S ON S.PROSEQ = P.SEQ
					 LEFT JOIN TB_COM_CODE C ON C.GRP_CD = 'OWN_OPT_ENGRAVE_PRICE' AND C.COM_NM = S.ENGRAVE
					 LEFT JOIN TB_COM_CODE D ON D.GRP_CD = 'OWN_OPT_STONE' AND D.COM_CD = S.READYMADESTONE

				WHERE	1=1
				AND	ISNULL(S.OPTIONYN,'N') = 'Y'
			) AA

GO


