USE [WOORIM_230215]
GO

/****** Object:  Table [dbo].[TB_COM_CODE]    Script Date: 2023-02-15 오후 12:38:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

BEGIN TRAN -- ROLLBACK COMMIT

-- 완료되면 삭제처리 
/*
	SELECT COUNT(*) FROM TB_COM_CODE_BACKUP_230215
	SELECT COUNT(*) FROM TB_COM_CODE
	DROP TABLE TB_COM_CODE_BACKUP_230215
*/

SELECT *
INTO TB_COM_CODE_BACKUP_230515
FROM TB_COM_CODE 

DROP TABLE TB_COM_CODE 

CREATE TABLE [dbo].[TB_COM_CODE](
	[GRP_CD] [varchar](50) NOT NULL,
	[COM_CD] [varchar](20) NOT NULL,
	[COM_NM] [varchar](255) NOT NULL,
	[SUB_CD] [nvarchar](20) NULL,
	[USE_YN] [char](1) NOT NULL,
	[DETL] [varchar](4000) NULL,
	[ORD] [int] NOT NULL,
	[REG_USER] [varchar](50) NOT NULL,
	[REG_DATE] [datetime] NOT NULL,
	[MOD_USER] [varchar](50) NULL,
	[MOD_DATE] [datetime] NULL,
	[SUB_CD_1] [nvarchar](100) NULL,
	[SUB_CD_2] [nvarchar](100) NULL,
	[SUB_CD_3] [nvarchar](100) NULL,
	[SUB_CD_4] [nvarchar](100) NULL,
 CONSTRAINT [PK_TB_COM_CODE] PRIMARY KEY CLUSTERED 
(
	[GRP_CD] ASC,
	[COM_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-- BACKUP UPLOAD
INSERT INTO TB_COM_CODE (GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE,MOD_USER,MOD_DATE,SUB_CD_1,SUB_CD_2,SUB_CD_3,SUB_CD_4)
SELECT GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE,MOD_USER,MOD_DATE,SUB_CD_1,SUB_CD_2,SUB_CD_3,SUB_CD_4
  FROM TB_COM_CODE_BACKUP_230215


-- 자사몰 옵션 공통코드 INSERT 
BEGIN TRAN -- COMMIT

INSERT INTO TB_COM_CODE(GRP_CD, COM_CD, COM_NM, SUB_CD, DETL, ORD, USE_YN, REG_DATE, REG_USER)
VALUES ('OWN_OPT_PRICE','ENGRAVE','각인 비용','10000','안/겉 각인시 발생하는 추가비용',0,'Y',GETDATE(), 'SYSTEM')

INSERT INTO TB_COM_CODE(GRP_CD, COM_CD, COM_NM, SUB_CD, DETL, ORD, USE_YN, REG_DATE, REG_USER)
VALUES ('OWN_OPT_PRICE','COLOR','색상 변경 비용','15000','RG/YG/WGX/CB->WG로 변경시 발생하는 추가비용',0,'Y',GETDATE(), 'SYSTEM')

INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','01','1월 가넷','','Y','',1,'SYSTEM',GETDATE())	
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','02','2월 자수정','','Y','',2,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','03','3월 아쿠아마린','','Y','',3,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','04','4월 다이아','','Y','',4,'SYSTEM',GETDATE())	
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','05','5월 에메랄드','','Y','',5	,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','06','6월 진주','','Y','',6,'SYSTEM',GETDATE())	
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','07','7월 루비','','Y','',7,'SYSTEM',GETDATE())	
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','08','8월 페리도트','','Y','',8	,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','09','9월 사파이어','','Y','',9	,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','10','10월 오팔','','Y','',10,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','11','11월 시트린','','Y','',11,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_STONE','12','12월 터키석','','Y','',12,'SYSTEM',GETDATE())

INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_PRD_INFO','WARRANTY_YN','보증서 제공여부','','Y','Y',1,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_PRD_INFO','MFG_COUNTRY','제조국','','Y','대한민국',2,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE,SUB_CD_1) VALUES ('OWN_PRD_INFO','PRECAUTIONS','착용 시 주의사항','','Y','충격이나 걸림 등에 의해 변형 및 파손될 수 있으므로 착용시 주의해주세요. 착용 후 화장품, 땀, 습기, 지문등의 이물질 제거 후 보관해주시기 바랍니다.',3,'SYSTEM',GETDATE(),
																										'일반적인 방수(간단히 손을 씻거나 물이 튀는 정도)이며, 땀이나 화장품등으로 인하여 변색될 수 있으며 특히 가죽은 물에서의 착용을 피해주세요.')
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_PRD_INFO','QA_STANDARD','품질보증기준','','Y','관련 법 및 소비자 분쟁해결 규정에 따름',4,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_PRD_INFO','AS_POC'     ,'A/S책임자','','Y','스톤헨지 고객센터',5,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_PRD_INFO','OPT_YN'     ,'특이사항','','Y','주문제작 가능여부(Y/N)',6,'SYSTEM',GETDATE())

INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_PRD_INFO','WARRANTY_YN','보증서 제공여부','','Y','Y',1,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_PRD_INFO','WARRANTY_YN','보증서 제공여부','','Y','Y',1,'SYSTEM',GETDATE())

INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_SLV_PRICE','01' ,'4000','N,A,B','Y','길이 11~20CM 추가금(SUB_CD:OPTION VIEW의 CATEGORY)',1,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_SLV_PRICE','02' ,'6000','N,A,B','Y','길이 21~30CM 추가금(SUB_CD:OPTION VIEW의 CATEGORY)',2,'SYSTEM',GETDATE())

INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_DETAIL','SLIVER_PRICE_01' ,'4000','N,A,B','Y','길이 11~20CM 추가금(SUB_CD:OPTION VIEW의 CATEGORY)',1,'SYSTEM',GETDATE())
INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_DETAIL','SLIVER_PRICE_02' ,'6000','N,A,B','Y','길이 21~30CM 추가금(SUB_CD:OPTION VIEW의 CATEGORY)',2,'SYSTEM',GETDATE())


INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_ETC','SYMBOL',
'＃,＆,＊,＠,§,※,☆,★,○,●,◎,◇,◆,□,■,△,▲,▽,▼,→,←,↑,↓,↔,〓,◁,◀,▷,▶,♤,♠,♡,♥,♧,♣,⊙,◈,▣,◐,◑,+,-,<,>,",'',♨,☏,☎,㉿,☜,☞,¶,†,‡,↕,↗,↙,↖,↘,♭,♩,♪,♬','','Y','각인 가능한 특수기호',1,'SYSTEM',GETDATE())

INSERT INTO TB_COM_CODE(GRP_CD,COM_CD,COM_NM,SUB_CD,USE_YN,DETL,ORD,REG_USER,REG_DATE) VALUES ('OWN_OPT_EXC_PROD','' ,'6000','N,A,B','Y','길이 21~30CM 추가금(SUB_CD:OPTION VIEW의 CATEGORY)',2,'SYSTEM',GETDATE())

DELETE FROM TB_COM_CODE WHERE GRP_CD = 'OWN_OPT_DETAIL'



ROLLBACK 