USE [WOORIM_230215]
GO

/****** Object:  Table [dbo].[LEADER_PRODUCT_IF]    Script Date: 2023-04-03 오후 18:18:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- 완료되면 삭제처리 
/*
	
	SELECT COUNT(*) FROM LEADER_PRODUCT_IF_BACKUP_230427
	SELECT COUNT(*) FROM LEADER_PRODUCT_IF
	DROP TABLE LEADER_PRODUCT_IF_BACKUP_230427

	SELECT *
	INTO LEADER_PRODUCT_IF_BACKUP_230427
	FROM LEADER_PRODUCT_IF 

	DROP TABLE LEADER_PRODUCT_IF 

	INSERT INTO LEADER_PRODUCT_IF (SET_GUBUN,MODEL_NO,MODEL_NM,STORE_SEQ,PRICE,SELL_PRICE,USE_YN,REG_DATE,IF_YN,IF_DATE,CHG_YN,CHG_DATE)
	SELECT SET_GUBUN,OWNMALL_MODEL_NO,OWNMALL_MODEL_NAME,STORE_SEQ,PRICE,SELL_PRICE,USE_YN,REG_DATE,IF_YN,IF_DATE,CHG_YN,CHG_DATE
	  FROM LEADER_PRODUCT_IF_BACKUP_230427
	 ORDER BY SEQ


*/



CREATE TABLE [DBO].[LEADER_PRODUCT_IF](
	[SEQ]					[INT] IDENTITY(1,1)	NOT NULL,
	[SET_GUBUN]				[VARCHAR](20)		NOT NULL,
	[MODEL_NO]				[VARCHAR](200)		NOT NULL,
	[MODEL_NM]				[VARCHAR](200)		NULL,
	[STORE_SEQ]				[INT]				NULL,
--	[BRAND_SEQ]				[INT]				NOT NULL,
--	[BRAND_NAME]			[VARCHAR](30)		NULL,
	[PRICE]					[INT]				NOT NULL,
	[SELL_PRICE]			[INT]				NOT NULL,
	[USE_YN]				[CHAR](1)			NULL,
	[REG_DATE]				[SMALLDATETIME]		NOT NULL,
	[IF_YN]					[VARCHAR](1)		NULL,
	[IF_DATE]				[SMALLDATETIME]		NULL,
	[CHG_YN]				[VARCHAR](1)		NULL,
	[CHG_DATE]				[SMALLDATETIME]		NULL,

 CONSTRAINT [PK_LEADER_PRODUCT_IF_SEQ] PRIMARY KEY CLUSTERED 
(
	[SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '자사몰 상품IF',			'USER', dbo, 'TABLE', LEADER_PRODUCT_IF;
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '순번',					'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [SEQ];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '세트구분(P-단일/S-세트)','USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [SET_GUBUN];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '제품별 키값, 모델번호',	'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [MODEL_NO];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '전시 모델명',			'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [MODEL_NM];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '매장 순번',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [STORE_SEQ];
-- EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '브랜드 순번',			'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [BRAND_SEQ];
-- EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '브랜드 명',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [BRAND_NAME];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '소비자가',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [PRICE];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '판매가',					'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [SELL_PRICE];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '사용여부',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [USE_YN];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '등록일시',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [REG_DATE];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '연동여부',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [IF_YN];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '연동일시',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [IF_DATE];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '변경여부',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [CHG_YN];
EXEC SP_ADDEXTENDEDPROPERTY 'MS_Description', '변경일시',				'USER', dbo, 'TABLE', LEADER_PRODUCT_IF, 'COLUMN', [CHG_DATE];

