USE [WOORIM_230215]
GO

/****** Object:  View [dbo].[LEADER_V_INV]    Script Date: 2023-03-23 오후 16:32:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



ALTER VIEW [dbo].[LEADER_V_INV] 
AS

-- 단품 재고 조회
SELECT A.MODEL_NM		AS MODEL_NM, 
	   ISNULL(C.QTY,0)	AS RI_QTY,
	   CASE WHEN B.ERP_GRP_MFG = '1' THEN 0 ELSE 999
		END			AS VI_QTY
  FROM LEADER_PRODUCT_IF	A WITH(NOLOCK)
 INNER JOIN PRODUCT			B WITH(NOLOCK) ON A.MODEL_NO = B.ERP_CD_ITEM
  LEFT JOIN HQINVENTORY		C WITH(NOLOCK) ON B.SEQ = C.PROSEQ
 WHERE A.SET_GUBUN = 'P'

UNION 

-- 세트 재고 조회 (테스트를 위해 100개로 고정)
SELECT DISTINCT MODELNO	AS MODEL_NM,
	   100		AS RI_QTY,
	   999		AS VI_QTY	
  FROM ECOMMERCESETPRODUCT WITH(NOLOCK)
   

GO


