	DECLARE @P_AS_IDX	VARCHAR(11),
			@OPENQUERY	NVARCHAR(MAX), 
			@Linked		NVARCHAR(MAX),
			@TSQL		NVARCHAR(MAX) 

	DECLARE @TB_AS_SPEC TABLE(
								  AS_IDX				INT
								, REG_DATE				SMALLDATETIME
								, CHARGE_NAME			NVARCHAR(255)
								, CUST_NAME				VARCHAR(50)	
								, CUST_PHONE			VARCHAR(100)
								, SALES_DATE			SMALLDATETIME
								, CER_NO				VARCHAR(50)
								, CHARGE_STOCK_DATE		SMALLDATETIME
								, CHARGE_IDX			INT
								, RECEPT_STORE_SEQ		INT
								, RECEPT_PRODUCT_SEQ	INT
							)		

	SELECT	@P_AS_IDX	= @AS_IDX
		,	@Linked		= 'MISSEC_LINK'
		,	@OPENQUERY	= 'SELECT AS_IDX, REG_DATE, CHARGE_NAME, CUST_NAME, CUST_PHONE, SALES_DATE, CER_NO, CHARGE_STOCK_DATE , CHARGE_IDX, RECEPT_STORE_SEQ, RECEPT_PRODUCT_SEQ FROM OPENQUERY('+ @Linked + ','''
		,	@TSQL		= 'SELECT A.AS_IDX, A.REG_DATE, A.CHARGE_NAME, A.CUST_NAME, A.CUST_PHONE, A.SALES_DATE, A.CER_NO, A.CHARGE_STOCK_DATE, A.CHARGE_IDX, A.RECEPT_STORE_SEQ, A.RECEPT_PRODUCT_SEQ 
							 FROM MIS_SEC.DBO.TB_AS_SPEC A WITH(NOLOCK)
							WHERE A.AS_IDX = '+ @P_AS_IDX+ ''')' 
		
	
	INSERT @TB_AS_SPEC EXEC (@OPENQUERY+@TSQL)
