DECLARE @L_STORE_SEQ INT;
DECLARE @L_ITEM       INT;
DECLARE @L_CATEGORY  INT;


DECLARE DELIVERY_CURSOR CURSOR FAST_FORWARD FOR 
SELECT  TOP 2 1, 2, 3 FROM TB_ECOM_MALL_ORDER

OPEN DELIVERY_CURSOR         
FETCH NEXT FROM DELIVERY_CURSOR INTO @L_STORE_SEQ, @L_ITEM, @L_CATEGORY
WHILE @@FETCH_STATUS = 0
BEGIN
   SELECT 'CURSOR 시작', @@FETCH_STATUS AS '@@FETCH_STATUS'
   -- NEXT FETCH 
   FETCH NEXT FROM DELIVERY_CURSOR INTO @L_STORE_SEQ, @L_ITEM, @L_CATEGORY
   --IF (@@FETCH_STATUS <> 0) BREAK;

   SELECT '커서 실행 완료'
            
END 
-- 커서 닫기
CLOSE DELIVERY_CURSOR

DEALLOCATE DELIVERY_CURSOR 
         

      
SELECT 'END', CURSOR_STATUS('global','DELIVERY_DETAIL_CURSOR'), XACT_STATE(), @@FETCH_STATUS AS '@@FETCH_STATUS'
