
SELECT NAME,CREATE_DATE,MODIFY_DATE,*
  FROM SYS.SQL_MODULES SM 
 INNER JOIN SYS.ALL_OBJECTS AO 
    ON SM.OBJECT_ID = AO.OBJECT_ID 
 WHERE 1=1
   AND NAME = 'MIS_ECOM_SALES_CONFIRM_UPLOAD_INSERT'
 ORDER BY AO.MODIFY_DATE DESC
