
-- lock 확인 (Mode가 x)
EXEC SP_LOCK -- SELECT * FROM SYS.sysprocesses WHERE BLOCKED > 0

DECLARE @SP_ID INT = 940

-- lock 추적
SELECT  P.SPID,
		P.LOGIN_TIME,
		P.LAST_BATCH,
		P.STATUS,
		P.PROGRAM_NAME,
		P.CMD,
		C.CLIENT_NET_ADDRESS,
		P.HOSTNAME,
		P.LOGINAME
  FROM SYS.SYSPROCESSES AS P
  INNER JOIN SYS.DM_EXEC_CONNECTIONS AS C ON P.SPID = C.SESSION_ID
 WHERE 1=1
   AND P.SPID = @SP_ID

-- LOCK 걸린 쿼리문 확인 
DBCC INPUTBUFFER ( @SP_ID );

-- LOCK 삭제 
KILL 378


